name: Trigger auto deployment for clarivise5

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/clarivise5-AutoDeployTrigger-8236d4b3-b0a0-4924-895d-818161887195.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLARIVISE5_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLARIVISE5_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLARIVISE5_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: clarivise5cr.azurecr.io
          registryUsername: ${{ secrets.CLARIVISE5_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLARIVISE5_REGISTRY_PASSWORD }}
          containerAppName: clarivise5
          resourceGroup: Clarivise5
          imageToBuild: clarivise5cr.azurecr.io/clarivise5:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


